In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.0.1+cu118


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([3])

In [10]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 3])

In [13]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 3])

### Random tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5859, 0.7429, 0.2675, 0.6199],
        [0.8130, 0.2751, 0.7508, 0.9660],
        [0.4932, 0.9376, 0.6727, 0.2416]])

In [17]:
random_tensor.ndim

2

In [18]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.ndim

3

Zeros and ones

In [19]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
range_tensor = torch.arange(start=0, end=1000, step=42)
range_tensor

tensor([  0,  42,  84, 126, 168, 210, 252, 294, 336, 378, 420, 462, 504, 546,
        588, 630, 672, 714, 756, 798, 840, 882, 924, 966])

In [24]:
torch.zeros_like(input=range_tensor)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [25]:
float_32_tensor = torch.tensor([2, 3], 
                               dtype=None, 
                               device=None, 
                               requires_grad=False)
print(float_32_tensor.dtype)
float_32_tensor

torch.int64


tensor([2, 3])

In [26]:
float_32_tensor = torch.tensor([2., 3.], 
                               dtype=None, 
                               device=None, 
                               requires_grad=False)
print(float_32_tensor.dtype)
float_32_tensor

torch.float32


tensor([2., 3.])

In [27]:
float_16_tensor = torch.tensor([2, 3], 
                               dtype=torch.float16, 
                               device=None, 
                               requires_grad=False)
float_16_tensor

tensor([2., 3.], dtype=torch.float16)

In [28]:
float_16_tensor = torch.tensor([2, 3], 
                               dtype=torch.float16, 
                               device="cuda", 
                               requires_grad=False)
float_16_tensor

tensor([2., 3.], device='cuda:0', dtype=torch.float16)

In [29]:
float_32_tensor.type(torch.float16)

tensor([2., 3.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
int_32_tensor = torch.tensor([2, 3])
int_32_tensor

tensor([2, 3])

In [ ]:
float_32_tensor + int_32_tensor

tensor([4., 6.])

### Manipulating tensors

In [ ]:
tensor = torch.tensor([1, 2, 3, ])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
res = 0
for i in range(tensor.shape[0]):
    res += tensor[i] * tensor[i]
res

CPU times: total: 0 ns
Wall time: 999 µs


tensor(14)

### Tensor aggregation

In [ ]:
tensor = torch.tensor([[2, 3, 4], 
                       [5, 6, 7]], dtype=torch.float32)
tensor.mean()

tensor(4.5000)

In [ ]:
tensor.ndim

2

In [ ]:
tensor.sum()

tensor(27.)

In [ ]:
tensor.argmax()

tensor(5)

In [ ]:
tensor.argmin()


tensor(0)

### Tensor transformations

In [ ]:
tensor = torch.arange(1., 10.)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tensor.reshape(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
tensor_view = tensor.view(3, 3)
tensor_view

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
tensor_view[1, 0:2] = 0
tensor_view

tensor([[1., 2., 3.],
        [0., 0., 6.],
        [7., 8., 9.]])

In [ ]:
tensor

tensor([1., 2., 3., 0., 0., 6., 7., 8., 9.])

In [ ]:
torch.stack([tensor, tensor], dim=0)

tensor([[1., 2., 3., 0., 0., 6., 7., 8., 9.],
        [1., 2., 3., 0., 0., 6., 7., 8., 9.]])

In [ ]:
torch.stack([tensor, tensor], dim=1)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [0., 0.],
        [0., 0.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [ ]:
x = torch.ones(1, 1, 4, 1, 5)
x.shape

torch.Size([1, 1, 4, 1, 5])

In [ ]:
x.squeeze().shape

torch.Size([4, 5])

In [ ]:
x.unsqueeze(dim=0).shape

torch.Size([1, 1, 1, 4, 1, 5])

In [ ]:
x_permuted = x.permute(2, 4, 0, 1, 3)
x_permuted.shape

torch.Size([4, 5, 1, 1, 1])

In [ ]:
x_permuted

tensor([[[[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]],



        [[[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]],



        [[[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]],



        [[[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]]])

In [ ]:
x[0, 0, 1, 0, 0] = 0
x

tensor([[[[[1., 1., 1., 1., 1.]],

          [[0., 1., 1., 1., 1.]],

          [[1., 1., 1., 1., 1.]],

          [[1., 1., 1., 1., 1.]]]]])

In [ ]:
x_permuted

tensor([[[[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]],



        [[[[0.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]],



        [[[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]],



        [[[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]],


         [[[1.]]]]])

### check for gpu

In [32]:
torch.cuda.is_available()

True

In [31]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [37]:
tensor = torch.tensor([1, 2, 3], device=device)
tensor.device

device(type='cuda', index=0)

In [40]:
tensor.cpu().numpy()

array([1, 2, 3], dtype=int64)